// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package cms

import (
	"database/sql"
	"time"
)

type Abteilung struct {
	ID   string
	Name string
}

type Account struct {
	ID                string
	Userid            string
	Type              string
	Provider          string
	Provideraccountid string
	RefreshToken      sql.NullString
	AccessToken       sql.NullString
	ExpiresAt         sql.NullInt32
	TokenType         sql.NullString
	Scope             sql.NullString
	IDToken           sql.NullString
	SessionState      sql.NullString
}

type Angebot struct {
	ID        string
	Title     string
	Subtitle  sql.NullString
	DateStart time.Time
	DateStop  time.Time
	Link      string
	Image     string
	Anzeigen  sql.NullBool
}

type Dokumente struct {
	ID           string
	Filename     string
	Extension    string
	DateModified time.Time
	Data         string
	Downloads    int32
}

type Job struct {
	ID     string
	Name   string
	Online bool
}

type Mitarbeiter struct {
	ID          string
	Name        string
	Short       string
	Image       bool
	Sex         string
	Tags        string
	Focus       string
	Abteilungid string
}

type Partner struct {
	ID    string
	Name  string
	Link  string
	Image string
}

type Session struct {
	ID           string
	Sessiontoken string
	Userid       string
	Expires      time.Time
}

type User struct {
	ID            string
	Name          sql.NullString
	Email         sql.NullString
	Emailverified sql.NullTime
	Image         sql.NullString
}

type Verificationtoken struct {
	Identifier string
	Token      string
	Expires    time.Time
}
