// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAbteilung(arg1) {
  return window['go']['main']['App']['CreateAbteilung'](arg1);
}

export function CreateAngebot(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateAngebot'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreateJob(arg1, arg2) {
  return window['go']['main']['App']['CreateJob'](arg1, arg2);
}

export function CreateMitarbeiter(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateMitarbeiter'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreatePartner(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreatePartner'](arg1, arg2, arg3);
}

export function DeleteAbteilung(arg1) {
  return window['go']['main']['App']['DeleteAbteilung'](arg1);
}

export function DeleteAngebot(arg1) {
  return window['go']['main']['App']['DeleteAngebot'](arg1);
}

export function DeleteJob(arg1) {
  return window['go']['main']['App']['DeleteJob'](arg1);
}

export function DeleteMitarbeiter(arg1) {
  return window['go']['main']['App']['DeleteMitarbeiter'](arg1);
}

export function DeletePartner(arg1) {
  return window['go']['main']['App']['DeletePartner'](arg1);
}

export function GenerateWarenlieferung() {
  return window['go']['main']['App']['GenerateWarenlieferung']();
}

export function GetAbteilung(arg1) {
  return window['go']['main']['App']['GetAbteilung'](arg1);
}

export function GetAbteilungen() {
  return window['go']['main']['App']['GetAbteilungen']();
}

export function GetAllMitarbeiter() {
  return window['go']['main']['App']['GetAllMitarbeiter']();
}

export function GetAllPartner() {
  return window['go']['main']['App']['GetAllPartner']();
}

export function GetAngebot(arg1) {
  return window['go']['main']['App']['GetAngebot'](arg1);
}

export function GetAngebote() {
  return window['go']['main']['App']['GetAngebote']();
}

export function GetCmsCounts() {
  return window['go']['main']['App']['GetCmsCounts']();
}

export function GetJob(arg1) {
  return window['go']['main']['App']['GetJob'](arg1);
}

export function GetJobs() {
  return window['go']['main']['App']['GetJobs']();
}

export function GetMitarbeiter(arg1) {
  return window['go']['main']['App']['GetMitarbeiter'](arg1);
}

export function GetPartner(arg1) {
  return window['go']['main']['App']['GetPartner'](arg1);
}

export function GetSeriennummer(arg1) {
  return window['go']['main']['App']['GetSeriennummer'](arg1);
}

export function SearchKunde(arg1) {
  return window['go']['main']['App']['SearchKunde'](arg1);
}

export function SendInfo(arg1, arg2) {
  return window['go']['main']['App']['SendInfo'](arg1, arg2);
}

export function SendWarenlieferung() {
  return window['go']['main']['App']['SendWarenlieferung']();
}

export function SyncAussteller() {
  return window['go']['main']['App']['SyncAussteller']();
}

export function SyncLabel() {
  return window['go']['main']['App']['SyncLabel']();
}

export function UpdateAbteilung(arg1, arg2) {
  return window['go']['main']['App']['UpdateAbteilung'](arg1, arg2);
}

export function UpdateAngebot(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['UpdateAngebot'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpdateJob(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateJob'](arg1, arg2, arg3);
}

export function UpdateMitarbeiter(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['UpdateMitarbeiter'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpdatePartner(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdatePartner'](arg1, arg2, arg3, arg4);
}
