// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateWarenlieferung():Promise<string>;

export function GetSeriennummer(arg1:string):Promise<string>;

export function SendInfo(arg1:string,arg2:string):Promise<string>;

export function SendWarenlieferung():Promise<string>;

export function SyncAussteller():Promise<string>;

export function SyncLabel():Promise<string>;
