// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sql} from '../models';
import {cms} from '../models';
import {main} from '../models';

export function CreateAbteilung(arg1:string):Promise<sql.Result|string>;

export function CreateAngebot(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<sql.Result|string>;

export function CreateJob(arg1:string,arg2:string):Promise<sql.Result|string>;

export function CreateMitarbeiter(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<sql.Result|string>;

export function CreatePartner(arg1:string,arg2:string,arg3:string):Promise<sql.Result|string>;

export function DeleteAbteilung(arg1:string):Promise<string>;

export function DeleteAngebot(arg1:string):Promise<string>;

export function DeleteJob(arg1:string):Promise<string>;

export function DeleteMitarbeiter(arg1:string):Promise<string>;

export function DeletePartner(arg1:string):Promise<string>;

export function GenerateWarenlieferung():Promise<string>;

export function GetAbteilung(arg1:string):Promise<cms.Abteilung|string>;

export function GetAbteilungen():Promise<Array<cms.Abteilung>|string>;

export function GetAllMitarbeiter():Promise<Array<cms.Mitarbeiter>|string>;

export function GetAllPartner():Promise<Array<cms.Partner>|string>;

export function GetAngebot(arg1:string):Promise<cms.Angebot|string>;

export function GetAngebote():Promise<Array<cms.Angebot>|string>;

export function GetCmsCounts():Promise<main.Counts|string>;

export function GetJob(arg1:string):Promise<cms.Job|string>;

export function GetJobs():Promise<Array<cms.Job>|string>;

export function GetMitarbeiter(arg1:string):Promise<cms.Mitarbeiter|string>;

export function GetPartner(arg1:string):Promise<cms.Partner|string>;

export function GetSeriennummer(arg1:string):Promise<string>;

export function SearchKunde(arg1:string):Promise<Array<main.Sg_Adressen>>;

export function SendInfo(arg1:string,arg2:string):Promise<string>;

export function SendWarenlieferung():Promise<string>;

export function SyncAussteller():Promise<string>;

export function SyncLabel():Promise<string>;

export function UpdateAbteilung(arg1:string,arg2:string):Promise<sql.Result|string>;

export function UpdateAngebot(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<sql.Result|string>;

export function UpdateJob(arg1:string,arg2:string,arg3:string):Promise<sql.Result|string>;

export function UpdateMitarbeiter(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<sql.Result|string>;

export function UpdatePartner(arg1:string,arg2:string,arg3:string,arg4:string):Promise<sql.Result|string>;
