// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateWarenlieferung() {
  return window['go']['main']['App']['GenerateWarenlieferung']();
}

export function GetSeriennummer(arg1) {
  return window['go']['main']['App']['GetSeriennummer'](arg1);
}

export function SendInfo(arg1, arg2) {
  return window['go']['main']['App']['SendInfo'](arg1, arg2);
}

export function SendWarenlieferung() {
  return window['go']['main']['App']['SendWarenlieferung']();
}

export function SyncAussteller() {
  return window['go']['main']['App']['SyncAussteller']();
}

export function SyncLabel() {
  return window['go']['main']['App']['SyncLabel']();
}
